version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-test
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mysql-test
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:6.2
    container_name: redis-test
    ports:
      - "6379:6379"


volumes:
  mysql_data:
