spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql-test
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: kokoa
      port: 6379
      password: redispassword

jwt:
  secretKey: 632488aa9012cba8a4e941209dee47bd27080939ab3ee6f5ff387efc3d41e46a
  refreshKey: 365a62bd652e5aa4cbeafb9f15d560e4accecda056cf73cd5480a96f1b76a1a3

server:
  port: 8080
  forward-headers-strategy: native
