global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kokoatalk-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api.kokoatalk.shop']
    scheme: https
    tls_config:
      insecure_skip_verify: true