name: Heroku CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # Java 21 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Gradle 빌드 실행
      - name: Build with Gradle
        run: ./gradlew build

      # Docker Container Registry에 로그인
      - name: Log in to Heroku Container Registry
        run: |
          echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com

      # Docker 이미지 빌드 및 Push
      - name: Build and Push Docker Image
        run: |
          docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      # Heroku 앱 릴리스
      - name: Release Heroku App
        run: |
          heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
